"""Default configuration values and environment fallback literals."""

from __future__ import annotations

from pathlib import Path


DEFAULT_FACE_LANDMARKER_MODEL_PATH = Path("models/face_landmarker.task")
DEFAULT_PREVIEW_WINDOW_NAME = "DroneAI Tello Front Camera"
DEFAULT_RECOGNITION_THRESHOLD = 0.6
DEFAULT_RECOGNITION_MARGIN_THRESHOLD = 0.03
DEFAULT_MIN_DETECTION_CONFIDENCE = 0.97
DEFAULT_RECOVERY_DETECTION_CONFIDENCE = 0.62
DEFAULT_DETECTION_NMS_THRESHOLD = 0.5
DEFAULT_TRACKING_TARGET_NAME = "Maksiu"
DEFAULT_TRACKING_TARGET_DISTANCE_M = 0.3
DEFAULT_TRACKING_FACE_WIDTH_M = 0.16
DEFAULT_TRACKING_CAMERA_HFOV_DEG = 82.6
DEFAULT_TRACKING_YAW_DEADBAND_PX = 60.0
DEFAULT_TRACKING_VERTICAL_DEADBAND_PX = 45.0
DEFAULT_TRACKING_VERTICAL_TARGET_Y_RATIO = 0.42
DEFAULT_TRACKING_BBOX_ANCHOR_Y_RATIO = 0.38
DEFAULT_TRACKING_DISTANCE_DEADBAND_M = 0.08
DEFAULT_TRACKING_FORWARD_GAIN = 90.0
DEFAULT_TRACKING_YAW_GAIN = 0.12
DEFAULT_TRACKING_VERTICAL_GAIN = 0.10
DEFAULT_TRACKING_LATERAL_GAIN = 0.65
DEFAULT_TRACKING_MIN_LATERAL_SPEED = 12
DEFAULT_TRACKING_MAX_FORWARD_SPEED = 30
DEFAULT_TRACKING_MAX_YAW_SPEED = 35
DEFAULT_TRACKING_MAX_VERTICAL_SPEED = 25
DEFAULT_TRACKING_MIN_VERTICAL_SPEED = 8
DEFAULT_TRACKING_MAX_LATERAL_SPEED = 20
DEFAULT_TRACKING_HEAD_POSE_ENABLED = True
DEFAULT_TRACKING_HEAD_YAW_DEADBAND_DEG = 12.0
DEFAULT_TRACKING_HEAD_POSE_MIN_CONFIDENCE = 0.5
DEFAULT_TRACKING_ORBIT_YAW_ASSIST_PX_PER_DEG = 3.5
DEFAULT_TRACKING_REACQUIRE_TIMEOUT_SECONDS = 1.8
DEFAULT_TRACKING_LOSS_SEARCH_TIMEOUT_SECONDS = 3.0
DEFAULT_TRACKING_SEARCH_YAW_SPEED = 28
DEFAULT_TRACKING_REACQUIRE_MATCH_MAX_DISTANCE_PX = 220.0
DEFAULT_TRACKING_REACQUIRE_MIN_CONFIDENCE = 0.9
DEFAULT_TRACKING_REACQUIRE_MIN_SCORE = 0.12
DEFAULT_TRACKING_PREFERRED_FRONTAL_YAW_DEG = 12.0
DEFAULT_TRACKING_PROFILE_RECENTER_YAW_GAIN = 0.60
DEFAULT_TRACKING_HEAD_YAW_TURN_GAIN = 0.333
DEFAULT_TAKEOFF_EXTRA_RISE_CM = 30

ENV_RECOGNITION_THRESHOLD = "0.5"
ENV_RECOGNITION_MARGIN_THRESHOLD = "0.03"
ENV_MIN_DETECTION_CONFIDENCE = "0.97"
ENV_RECOVERY_DETECTION_CONFIDENCE = "0.62"
ENV_DETECTION_NMS_THRESHOLD = "0.6"
ENV_TRACKING_TARGET_DISTANCE_M = "0.6"
ENV_TRACKING_FACE_WIDTH_M = "0.16"
ENV_TRACKING_CAMERA_HFOV_DEG = "82.6"
ENV_TRACKING_YAW_DEADBAND_PX = "60"
ENV_TRACKING_VERTICAL_DEADBAND_PX = "45"
ENV_TRACKING_VERTICAL_TARGET_Y_RATIO = "0.42"
ENV_TRACKING_BBOX_ANCHOR_Y_RATIO = "0.38"
ENV_TRACKING_DISTANCE_DEADBAND_M = "0.08"
ENV_TRACKING_FORWARD_GAIN = "90"
ENV_TRACKING_YAW_GAIN = "0.12"
ENV_TRACKING_VERTICAL_GAIN = "0.10"
ENV_TRACKING_LATERAL_GAIN = "0.65"
ENV_TRACKING_MIN_LATERAL_SPEED = "12"
ENV_TRACKING_MAX_FORWARD_SPEED = "30"
ENV_TRACKING_MAX_YAW_SPEED = "35"
ENV_TRACKING_MAX_VERTICAL_SPEED = "25"
ENV_TRACKING_MIN_VERTICAL_SPEED = "8"
ENV_TRACKING_MAX_LATERAL_SPEED = "20"
ENV_TRACKING_HEAD_POSE_ENABLED = "true"
ENV_TRACKING_HEAD_YAW_DEADBAND_DEG = "12"
ENV_TRACKING_HEAD_POSE_MIN_CONFIDENCE = "0.5"
ENV_TRACKING_ORBIT_YAW_ASSIST_PX_PER_DEG = "3.5"
ENV_TRACKING_REACQUIRE_TIMEOUT_SECONDS = "1.8"
ENV_TRACKING_LOSS_SEARCH_TIMEOUT_SECONDS = "3.0"
ENV_TRACKING_SEARCH_YAW_SPEED = "28"
ENV_TRACKING_REACQUIRE_MATCH_MAX_DISTANCE_PX = "220"
ENV_TRACKING_REACQUIRE_MIN_CONFIDENCE = "0.9"
ENV_TRACKING_REACQUIRE_MIN_SCORE = "0.12"
ENV_TRACKING_PREFERRED_FRONTAL_YAW_DEG = "12"
ENV_TRACKING_PROFILE_RECENTER_YAW_GAIN = "0.60"
ENV_TRACKING_HEAD_YAW_TURN_GAIN = "0.38"
ENV_TAKEOFF_EXTRA_RISE_CM = "30"
