"""Runtime and UI timing constants."""

from __future__ import annotations


DEFAULT_API_HOST = "127.0.0.1"
DEFAULT_API_PORT = 8000
CLI_IDLE_SLEEP_SECONDS = 1.0
PROCESSING_THREAD_JOIN_TIMEOUT_SECONDS = 5.0
API_START_TIMEOUT_SECONDS = 5.0
API_START_POLL_INTERVAL_SECONDS = 0.05
API_THREAD_JOIN_TIMEOUT_SECONDS = 5.0
REGISTRATION_SERIES_SAMPLE_COUNT = 5
REGISTRATION_SERIES_TIMEOUT_SECONDS = 6.0
REGISTRATION_FRAME_WAIT_SECONDS = 0.08
REGISTRATION_SAMPLE_INTERVAL_SECONDS = 0.12
REGISTRATION_MIN_FACE_AREA_PX = 10_000
PROCESSING_ERROR_SLEEP_SECONDS = 0.05
TELLO_POST_TAKEOFF_STREAM_DELAY_SECONDS = 0.5
TELLO_STREAM_START_DELAY_SECONDS = 0.2

GUI_WINDOW_GEOMETRY = "1360x860"
GUI_MIN_WIDTH_PX = 1100
GUI_MIN_HEIGHT_PX = 700
GUI_OUTER_PADDING_PX = 12
GUI_COLUMN_PREVIEW_WEIGHT = 3
GUI_COLUMN_SIDEBAR_WEIGHT = 1
GUI_WRAP_LENGTH_PX = 320
GUI_REFRESH_INTERVAL_MS = 80
GUI_PREVIEW_THUMBNAIL_SIZE = (920, 780)
GUI_TITLE_FONT_SIZE = 16
GUI_SECTION_FONT_SIZE = 11
