"""Tracking computation constants."""

from __future__ import annotations


INITIAL_SEARCH_DIRECTION = 1
NO_TARGET_SEARCH_DIRECTION_RIGHT = "right"
NO_TARGET_SEARCH_DIRECTION_LEFT = "left"
MISSING_SIMILARITY_SCORE = -1.0
PINHOLE_FOCAL_LENGTH_DIVISOR = 2.0
CENTER_DIVISOR = 2.0
REACQUIRE_IOU_WEIGHT = 2.2
SEARCH_DIRECTION_DEADBAND_DIVISOR = 2.0
