"""Vision model, detection, embedding, and overlay constants."""

from __future__ import annotations

import numpy as np


SFACE_INPUT_SIZE = (112, 112)
FACE_CHIP_MARGIN_RATIO = 0.15
RECOGNITION_TOP_K_SAMPLES = 3
RECOGNITION_BEST_SAMPLE_WEIGHT = 0.65
RECOGNITION_MEAN_SAMPLE_WEIGHT = 0.35

DETECTOR_DEFAULT_MIN_CONFIDENCE = 0.8
DETECTOR_DEFAULT_NMS_THRESHOLD = 0.35
DETECTOR_FALLBACK_MIN_CONFIDENCE = 0.62
DETECTOR_RECOVERY_CONFIDENCE_DELTA = 0.22
MEDIAPIPE_DETECTOR_CONFIDENCE_CAP = 0.72
MEDIAPIPE_SHORT_RANGE_MODEL_SELECTION = 0
MEDIAPIPE_FULL_RANGE_MODEL_SELECTION = 1
HAAR_FRONTAL_SCALE_FACTOR = 1.1
HAAR_FRONTAL_MIN_NEIGHBORS = 6
HAAR_FRONTAL_MIN_SIZE = (44, 44)
HAAR_FRONTAL_CONFIDENCE = 0.7
HAAR_PROFILE_SCALE_FACTOR = 1.12
HAAR_PROFILE_MIN_NEIGHBORS = 7
HAAR_PROFILE_MIN_SIZE = (52, 52)
HAAR_PROFILE_CONFIDENCE = 0.64
RECOVERY_MIN_FACE_SIZE_PX = 52
RECOVERY_MIN_FACE_AREA_PX = 3_200
RECOVERY_PROFILE_MIN_ASPECT_RATIO = 0.58
RECOVERY_PROFILE_MAX_ASPECT_RATIO = 1.18
RECOVERY_FRONTAL_MIN_ASPECT_RATIO = 0.65
RECOVERY_FRONTAL_MAX_ASPECT_RATIO = 1.45
NMS_MIN_CANDIDATES = 2

HEAD_POSE_LANDMARK_INDEX = {
    "nose_tip": 1,
    "chin": 152,
    "left_eye_outer": 33,
    "right_eye_outer": 263,
    "mouth_left": 61,
    "mouth_right": 291,
}
HEAD_POSE_MODEL_POINTS = np.array(
    [
        (0.0, 0.0, 0.0),
        (0.0, -63.6, -12.5),
        (-43.3, 32.7, -26.0),
        (43.3, 32.7, -26.0),
        (-28.9, -28.9, -24.1),
        (28.9, -28.9, -24.1),
    ],
    dtype=np.float64,
)
HEAD_POSE_NUM_FACES = 1
HEAD_POSE_CONFIDENCE_CAP = 0.35
HEAD_POSE_ROI_PAD_X_RATIO = 0.35
HEAD_POSE_ROI_PAD_Y_RATIO = 0.4
HEAD_POSE_DIST_COEFFS_SHAPE = (4, 1)
HEAD_POSE_SINGULAR_EPSILON = 1e-6
HEAD_POSE_MAX_ABS_POSE_DEG = 90.0
HEAD_POSE_YAW_2D_SCALE_DEG = 90.0
HEAD_POSE_MAX_ABS_2D_YAW_DEG = 45.0
HEAD_POSE_EYE_LINE_DIVISOR = 2.0

COLOR_KNOWN_FACE_BGR = (0, 200, 0)
COLOR_UNKNOWN_FACE_BGR = (0, 165, 255)
COLOR_EMBEDDING_ERROR_BGR = (0, 0, 255)
COLOR_TRACKING_TARGET_BGR = (255, 140, 0)
COLOR_MESH_POINT_BGR = (255, 255, 0)
COLOR_MESH_KEYPOINT_BGR = (0, 255, 255)
BOX_LINE_THICKNESS_PX = 2
MESH_POINT_RADIUS_PX = 1
MESH_KEYPOINT_RADIUS_PX = 2
MESH_KEYPOINT_STRIDE = 40
FILLED_CIRCLE_THICKNESS = -1
LABEL_Y_OFFSET_PX = 10
LABEL_MIN_Y_PX = 20
LABEL_FONT_SCALE = 0.5
LABEL_LINE_THICKNESS_PX = 2
